# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Lean Kanban Central Europe"

email: "lkce@it-agile.de"
description: "World's biggest conference on Lean and Kanban!"
baseurl: ""
url: "http://www.leankanbance.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "it-agile GmbH"
organizerAlternateName: "it-agile"
organizerDescription: "Consultancy for Agile methods"
organizerEmail: "lkce@it-agile.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.it-agile.de"

# Head
metaKeywords: "event, kanban, lean, modern management, change, it-agile, LKU, agile, hamburg"
twitterAccount: "@LeanKanbanCE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/cfp-lkce17"
c4sponsorsUrl: "/assets/Sponsoring_LKCE17.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/socialevent/", text: "Social Event"}
bottomNavigationLinks:
  - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
  - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "aligned.png"
heroTitle: "Lean Kanban Central Europe <typeout>"
eventDate: "7th + 8th November, 2017"
typeoutTextValues: '"", "2017"'
typeoutFallback: "2017"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Lean Kanban Central Europe"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Come and join us at the world’s most popular Lean Kanban conference of this world wide series. Two days packed with inspiring talks, workshops and networking opportunities."}
 - {title: "Social Event", image: "socialevent.jpg", text: "Join us for an evening of exchanging ideas, meeting new people and your favorite speaker while having a beer!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Want to dig even deeper? Stay in Hamburg and attend one of many workshop that will take place on Nov. 9th. Stay tuned for more information!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of Lean and Kanban"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "from all over the world"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "plus lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Keynote Speakers Block
keynoteSpeakersImage: "speakers.jpg"
keynoteSpeakersCount: 3
keynoteSpeakersTitle: "Keynote Speakers"
keynoteSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Curio-Haus"
eventLocationLink: "http://www.koflerkompanie.com/locations/hamburg/curiohaus/"
eventStreetAddress: "Rothenbaumchaussee 13"
eventAddressLocality: "Hamburg"
eventAddressLocalityRegion: "Hamburg"
eventPostalCode: "20148"
eventAddressCountry: "Germany"
eventStartTime: "2017-11-07T09:30"
eventDoorTime: "09:00"
eventEndTime: "2017-11-08T18:00"
eventPlaceCoordinates: "53.565018, 9.989006"
mapCenterCoordinates: "53.565018, 9.989006"
mapMobileCenterCoordinates: "53.565018, 9.989006"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Curio-Haus"
venueFeatures: ["4 rooms", "Lounge to relax and talk", "Located close to the Außenalster"]

# Tweets Feed Block
tweetsFeedImage: "direction-details.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "LKCE17"
twitterFeed: "http://leankanbance.com/tweetledee/searchjson.php?q=#lkce17&rt=recent"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of April. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Single Ticket"
  price: "1000"
  priceCurrency: "EUR (excl. 19% VAT)"
  ticketsNumber: ""
  ribbon: ""
  buyButtonLink: "http://ti.to/lkce/lkce17"
  buyButtonText: "Buy Now - the price will go up"
  ticketContentList: ["2 Days", "3 Tracks", "Social Event"]
  validFrom: "2017-11-25T10:00"
  validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "http://twitter.com/LeanKanbanCE", icon: "twitter"}
 - {link: "http://facebook.com/LeanKanbanCE", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://it-agile.de", text: "it-agile GmbH"}
   - {link: "http://leankanban.com", text: "Lean Kanban Inc."}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lkce@it-agile.de", text: "lkce@it-agile.de"}
 -
  title: "Legal"
  links:
   - {permalink: "/impressum/", text: "Impressum"}
   - {permalink: "/termsoftrade/", text: "Terms of Trade"}
   - {permalink: "/datenschutz/", text: "Datenschutz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "lkce"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "It all started 2011 in Munich and since then Lean Kanban Central Europe grew to the biggest and most popular conference on Lean and Kanban. Our mission has always been and will be again in 2017 to host an unforgetable event for system thinkers, managers, leaders, out-of-the-box-thinkers, entrepreneurs, product developers, and people who care about the way they work."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "53.565018, 9.989006"
logisticsMapMobileCenterCoordinates: "53.565018, 9.989006"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Hamburg"
directionDetailsCards:
 - {title: "From the Airport", information: 'The airport is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.hamburg-airport.de/en/bus_rail_and_transfer.php">airport website</a>.'}
 - {title: "Public Transit", information: 'Go to Hamburg Dammtor for public transportation to the central station, the airport or anywhere else in Hamburg.'}

directionDetailsWideCards:

# Logistics Hotels Block
hotelsTitle: "Hotels"

# Hackathon
hackathonTitle: "Social Event"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
ackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
